### ISSUE TITLE
duckdb_value_string can't be compared to fortran strings

### ISSUE THREAD

**Issue by lucin81** [freevryheid/duckdb#10]
```fortran 
call check(error, duckdb_value_string(result, 0, 0) == 'hello')
if (allocated(error)) return
```

This example above doesn't compile because the result of `duckdb_value_string` is a `type(duckdb_string)`. Should we return a `character` instead similar to other value functions that return the corresponding Fortran type?

**Comment by freevryheid** [comment]
I believe this is now fixed, prelim. testing confirmed. May still need to check if result is c_associated.

**Comment by freevryheid** [comment]
done
