### ISSUE TITLE
read/write parquet files

### ISSUE THREAD

**Issue by freevryheid** [freevryheid/duckdb#5]
This was our primary objective. 

I propose writing a test that will:
+ Open a memory database.
+ Create a table: CREATE TABLE test AS SELECT * FROM 'test.parquet'; 
+ Manipulate data in the table: 
+ Write the table to file: COPY (SELECT * FROM test) TO 'result.parquet' (FORMAT 'parquet');
+ Close the database
+ Validate result.paquet

**Comment by lucin81** [comment]
sounds good. I'll put together the test and we can see what is missing.
